[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.120.0"  # Updated Hugo version
  HUGO_ENV = "production"
  GO_VERSION = "1.20"

[context.production.environment]
  HUGO_ENV = "production"