[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.120.4"  # Updated Hugo version
  HUGO_ENV = "production"
  GO_VERSION = "1.20"

[context.production.environment]
  HUGO_ENV = "production"
    HUGO_VERSION = "0.120.4"  # Or the latest version compatible with your theme
